stgEngChannelOfTDSrv: "TD@StgEngChannel@Trade"
stgEngChannelOfRiskMgr: "RISK@StgEngChannel@Trade"
stgEngChannelOfWebSrv: "WEBSRV@StgEngChannel@Trade"

stgId: 10000

tdEngParam: host=192.168.222.188; port=0; db=; username=root; password=taosdata; connPoolSize=4

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=192.168.222.188; port=3306; username=root; password=Tentap123
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

webSrv: localhost

stgInstTaskDispatcherParam: moduleName=StgInstTaskDispatcher;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=4

tblMonitorOfSymbolInfo: "symbolCode in ('600000', 'a2309', '002230', '000725', '600600', '600519', '601398', '601288', '603123',  '000002',  'SF2305', 'IC2302', 'WH2309', 'SR2309', 'AP2404', 'IF2312', 'IC2312', 'IC2309', 'a2403', 'c2403', 'b2403')"

monitorSymbolTableChanges: false  
milliSecIntervalOfTBLMonitorOfSymbolInfo: 10000
milliSecIntervalOfTBLMonitorOfStgInstInfo: 10000

milliSecIntervalOfSyncTask: 5

timeoutOfQueryHisMD: 60000

rootDirOfStgPrivateData: /dev/shm

algoMgr:
  taskDispatcherParam: moduleName=algoMgrTaskDispatcher;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=1;preCreateTaskSpecificThreadPool=1
  usIntervalOfTaskHandler: 1

logger: 
  queueSize: 10000
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqstg/bqstg-10000"
      outputFilename: "bqstg-10000"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
