stgEngChannelOfTDSrv: "TD@StgEngChannel@Trade"
stgEngChannelOfRiskMgr: "RISK@StgEngChannel@Trade"
stgEngChannelOfWebSrv: "WEBSRV@StgEngChannel@Trade"

stgId: 1

tdEngParam: host=192.168.222.188; port=0; db=; username=root; password=taosdata; connPoolSize=4

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=192.168.222.188; port=3306; username=root; password=Tentap123
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

webSrv: localhost

stgInstTaskDispatcherParam: moduleName=StgInstTaskDispatcher;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=4

tblMonitorOfSymbolInfo: "symbolType in ('CN_MainBoard', 'CN_Futures', 'CN_TechBoard', 'CN_StartupBoard', 'CN_SecondBoard')"

monitorSymbolTableChanges: false
milliSecIntervalOfTBLMonitorOfSymbolInfo: 10000
milliSecIntervalOfTBLMonitorOfStgInstInfo: 10000

milliSecIntervalOfSyncTask: 5

timeoutOfQueryHisMD: 60000

rootDirOfStgPrivateData: /dev/shm

algoMgr:
  taskDispatcherParam: moduleName=algoMgrTaskDispatcher;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=1 

logger: 
  queueSize: 10000
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqstg/bqstg-1"
      outputFilename: "bqstg-1"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
