marketCodeGroup: [SHFE, CZCE, DCE, CFFEX, INE, GFEX]
symbolType: Futures

secOfWaitForSymbolTable: 15

subAllMarketData: true

saveTickers: false
saveTrades: false
saveOrders: false
saveBooks: false

enableSymbolTableMaint: true

createBid1Ask1ByTickers: true
createLastPriceByTickers: true

checkIFExchTsOfMDIsInc: false

loggerThresholdOfTopicRecvTimes: 100

api:
  apiName: CTP
  flowPath: data/MD/CTP/flowpath-md
  frontAddr: tcp://180.168.146.187:10211
# frontAddr: tcp://180.168.146.187:10131
  brokerID: 9999
  userID: 
  password:

apiOfTD:
  flowPath: data/MD/CTP/flowpath-td
  frontAddr: tcp://180.168.146.187:10201
# frontAddr: tcp://180.168.146.187:10130
  appID: simnow_client_test
  authCode: 0000000000000000
  brokerID: 9999
  userID: 209057
  password: 1122@3344X

simedMode:
  enable: false
  playbackMD: "symbolCode IN ('bu2307', 'ag2307', 'hc2307')"
  playbackSpeed: 10000
  playbackDateTimeStart: 20230120T000000
  playbackDateTimeEnd: 20230123T230000
  msIntervalOfCheckCacheNum: 1000
  cacheNumLimit: 5
  secOfCacheMD: 3600
  secOffsetOfExchAndLocalTs: 60

rawMDHandlerParam: moduleName=rawMDHandler; numOfUnprocessedTaskAlert=1000; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=4

mdStorageSvcParam: moduleName=mdStorageSvc; numOfUnprocessedTaskAlert=1000; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=4
numOfMDWrittenToTDEngAtOneTime: 100

tdEngParam: host=192.168.222.188; port=0; db=; username=root; password=taosdata; connPoolSize=4

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=192.168.222.188; port=3306; username=root; password=Tentap123
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

logger: 
  queueSize: 10000
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqmd/bqmd-ctp"
      outputFilename: "bqmd-ctp"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
